version: '2'
services:
  #Zookeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
  
  #Kafka broker Service
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "service-registry:10:1,socket-gateway:10:1,exchanges:10:1,bot-sessions:10:1,exchange-accounts:10:1"
    volumes:
      - kafka-data:/var/lib/kafka/data

  #InfluxDB Service
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    # tty: true
    ports:
      - "8086:8086"
    environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: admin
        DOCKER_INFLUXDB_INIT_PASSWORD: password
        DOCKER_INFLUXDB_INIT_ORG: simple-trader
        DOCKER_INFLUXDB_INIT_BUCKET: simple-trader
    volumes:
      - influxdb-data:/var/lib/influxdb2

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass password
    ports:
     - "6379:6379"
    volumes:
     - redis-data:/var/lib/redis
    environment:
     - REDIS_REPLICATION_MODE=master

networks:
  default:
    name: 'simple-trader'
    external: true

#Volumes
volumes:
  zookeeper-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/zookeeper
  kafka-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/kafka
  influxdb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/influxdb
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis
